package jhlog

import (
	"encoding/binary"
	"hash/crc32"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestV1ReaderUsesNewestValidStateAndReadsWrappedChunks(t *testing.T) {
	path, firstPosition := writeV1Fixture(t)

	values, result, err := readV1MemoryValues(path)
	if err != nil {
		t.Fatalf("StreamFileWithResult() error = %v", err)
	}
	if result.Version != CurrentFormatMajor || result.FormatMajor != 1 || result.FormatMinor != 0 {
		t.Fatalf("version = %d (%d.%d)", result.Version, result.FormatMajor, result.FormatMinor)
	}
	if result.Status != SegmentStatusOpenClean || result.CommittedChunks != 2 {
		t.Fatalf("result = %+v", result)
	}
	if len(values) != 2 || values[0] != 11 || values[1] != 22 {
		t.Fatalf("memory values = %v", values)
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	raw[int(v1SuperblockBOffset+v1SuperblockBytes-1)] ^= 0xff
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		t.Fatal(err)
	}

	values, result, err = readV1MemoryValues(path)
	if err != nil {
		t.Fatalf("fallback StreamFileWithResult() error = %v", err)
	}
	if result.CommittedChunks != 1 || len(values) != 1 || values[0] != 11 {
		t.Fatalf("fallback result = %+v, values = %v, first position = %d", result, values, firstPosition)
	}
}

func TestV1ReaderTreatsUnallocatedArenaTailAsCircularGap(t *testing.T) {
	path := writeV1FixtureWithUnallocatedTail(t)

	values, result, err := readV1MemoryValues(path)
	if err != nil {
		t.Fatalf("StreamFileWithResult() error = %v", err)
	}
	if result.Status != SegmentStatusOpenClean || result.CommittedChunks != 2 {
		t.Fatalf("result = %+v", result)
	}
	if len(values) != 2 || values[0] != 11 || values[1] != 22 {
		t.Fatalf("memory values = %v", values)
	}
}

func TestV1ReaderRejectsOversizedStoredPayloadBeforeReadingIt(t *testing.T) {
	path, firstPosition := writeV1Fixture(t)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	chunkOffset := int(v1ArenaOffset) + firstPosition
	binary.LittleEndian.PutUint32(raw[chunkOffset+16:chunkOffset+20], uint32(maxStoredChunkSize+1))
	binary.LittleEndian.PutUint32(raw[chunkOffset+32:chunkOffset+36], crc32.ChecksumIEEE(raw[chunkOffset:chunkOffset+32]))
	for _, offset := range []int{int(v1SuperblockAOffset), int(v1SuperblockBOffset)} {
		binary.LittleEndian.PutUint64(raw[offset+16:offset+24], uint64(maxStoredChunkSize*2))
		binary.LittleEndian.PutUint32(
			raw[offset+int(v1SuperblockBytes)-4:offset+int(v1SuperblockBytes)],
			crc32.ChecksumIEEE(raw[offset:offset+int(v1SuperblockBytes)-4]),
		)
	}
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		t.Fatal(err)
	}

	_, err = StreamFileWithResult(path, nil)
	if err == nil || !strings.Contains(err.Error(), "stored length") {
		t.Fatalf("error = %v", err)
	}
}

func TestV1ReaderRejectsValidChecksumSuperblocksWithImpossibleState(t *testing.T) {
	tests := []struct {
		name   string
		mutate func([]byte)
	}{
		{name: "zero generation", mutate: func(block []byte) { binary.LittleEndian.PutUint64(block[8:16], 0) }},
		{name: "zero arena", mutate: func(block []byte) { binary.LittleEndian.PutUint64(block[16:24], 0) }},
		{name: "head beyond arena", mutate: func(block []byte) { binary.LittleEndian.PutUint64(block[24:32], math.MaxUint64) }},
		{name: "tail beyond arena", mutate: func(block []byte) { binary.LittleEndian.PutUint64(block[32:40], math.MaxUint64) }},
		{name: "used beyond arena", mutate: func(block []byte) { binary.LittleEndian.PutUint64(block[40:48], math.MaxUint64) }},
		{name: "first after next", mutate: func(block []byte) {
			binary.LittleEndian.PutUint64(block[48:56], 9)
			binary.LittleEndian.PutUint64(block[56:64], 8)
		}},
		{name: "count differs from sequence window", mutate: func(block []byte) {
			binary.LittleEndian.PutUint64(block[64:72], 1)
			binary.LittleEndian.PutUint64(block[48:56], 2)
			binary.LittleEndian.PutUint64(block[56:64], 8)
		}},
		{name: "wraps exceed evicted chunks", mutate: func(block []byte) {
			binary.LittleEndian.PutUint64(block[72:80], 2)
			binary.LittleEndian.PutUint64(block[80:88], 1)
		}},
		{name: "evicted bytes exceed generated bytes", mutate: func(block []byte) {
			binary.LittleEndian.PutUint64(block[88:96], math.MaxUint64)
		}},
		{name: "generated bytes disagree with retained arena bytes", mutate: func(block []byte) {
			generated := binary.LittleEndian.Uint64(block[96:104])
			binary.LittleEndian.PutUint64(block[96:104], generated+1)
		}},
		{name: "retained bytes before arena", mutate: func(block []byte) {
			binary.LittleEndian.PutUint64(block[104:112], uint64(v1ArenaOffset)-1)
		}},
		{name: "retained bytes beyond arena", mutate: func(block []byte) {
			arenaCapacity := binary.LittleEndian.Uint64(block[16:24])
			binary.LittleEndian.PutUint64(block[104:112], uint64(v1ArenaOffset)+arenaCapacity+1)
		}},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			path, _ := writeV1Fixture(t)
			raw, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			for _, offset := range []int{int(v1SuperblockAOffset), int(v1SuperblockBOffset)} {
				block := raw[offset : offset+int(v1SuperblockBytes)]
				test.mutate(block)
				binary.LittleEndian.PutUint32(block[len(block)-4:], crc32.ChecksumIEEE(block[:len(block)-4]))
			}
			if err := os.WriteFile(path, raw, 0o600); err != nil {
				t.Fatal(err)
			}

			result, err := StreamFileWithResult(path, nil)
			if err == nil || result.Status != SegmentStatusCorrupt || !strings.Contains(err.Error(), "no valid 1.0 superblock") {
				t.Fatalf("result = %+v, error = %v", result, err)
			}
		})
	}
}

func TestV1ReaderRejectsChunkWithoutValidCommit(t *testing.T) {
	path, firstPosition := writeV1Fixture(t)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	chunkOffset := int(v1ArenaOffset) + firstPosition
	storedLength := int(binary.LittleEndian.Uint32(raw[chunkOffset+16 : chunkOffset+20]))
	trailerOffset := chunkOffset + v1ChunkHeaderBytes + storedLength
	raw[trailerOffset] ^= 0xff
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		t.Fatal(err)
	}

	result, err := StreamFileWithResult(path, nil)
	if err == nil || result.Status != SegmentStatusCorrupt || !strings.Contains(err.Error(), "commit trailer") {
		t.Fatalf("result = %+v, error = %v", result, err)
	}
}

func TestV1ReaderDecodesEmbeddedLogGrowthHistoryAndLatestLiveSummary(t *testing.T) {
	path, _ := writeV1Fixture(t)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	copy(raw[int(v1HistoryOffset):], marshalV1GrowthHistoryForTest())
	copy(raw[int(v1LiveAOffset):], marshalV1GrowthLiveForTest(1, 10, false))
	copy(raw[int(v1LiveBOffset):], marshalV1GrowthLiveForTest(2, 20, true))
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		t.Fatal(err)
	}

	result, err := StreamFileWithResult(path, nil)
	if err != nil {
		t.Fatal(err)
	}
	growth := result.LogGrowth
	if growth == nil || growth.Generation != 7 || growth.CapturedAtMS != 1_800_000_000_000 {
		t.Fatalf("growth = %+v", growth)
	}
	if len(growth.Sessions) != 1 || growth.Sessions[0].GeneratedBytes != 500 || !growth.Sessions[0].Recovered {
		t.Fatalf("sessions = %+v", growth.Sessions)
	}
	if len(growth.Days) != 1 || growth.Days[0].OverflowCount != 6 {
		t.Fatalf("days = %+v", growth.Days)
	}
	if growth.Live == nil || growth.Live.GeneratedBytes != 20 || !growth.Live.Completed {
		t.Fatalf("live = %+v", growth.Live)
	}
}

func TestV1ReaderFallsBackFromDamagedLiveSummaryWithoutRejectingLog(t *testing.T) {
	path, _ := writeV1Fixture(t)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	copy(raw[int(v1LiveAOffset):], marshalV1GrowthLiveForTest(1, 10, false))
	damaged := marshalV1GrowthLiveForTest(2, 20, true)
	damaged[len(damaged)-1] ^= 0xff
	copy(raw[int(v1LiveBOffset):], damaged)
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		t.Fatal(err)
	}

	result, err := StreamFileWithResult(path, nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.LogGrowth == nil || result.LogGrowth.Live == nil || result.LogGrowth.Live.GeneratedBytes != 10 {
		t.Fatalf("growth = %+v", result.LogGrowth)
	}
	if !strings.Contains(strings.Join(result.Warnings, "\n"), "live summary") {
		t.Fatalf("warnings = %v", result.Warnings)
	}
}

func TestV1ReaderIsolatesEveryInvalidGrowthHistoryHeaderFromEventData(t *testing.T) {
	tests := []struct {
		name   string
		mutate func([]byte)
	}{
		{name: "unsupported schema", mutate: func(history []byte) { history[5]++ }},
		{name: "invalid header size", mutate: func(history []byte) {
			binary.LittleEndian.PutUint16(history[6:8], v1HistoryHeaderBytes-1)
		}},
		{name: "payload above reserved area", mutate: func(history []byte) {
			binary.LittleEndian.PutUint32(history[8:12], v1HistoryMaximumBytes+1)
		}},
		{name: "unsupported session record size", mutate: func(history []byte) {
			binary.LittleEndian.PutUint16(history[12:14], v1HistorySessionBytes-1)
			recalculateV1GrowthHistoryCRC(history)
		}},
		{name: "too many sessions", mutate: func(history []byte) {
			binary.LittleEndian.PutUint32(history[16:20], v1EmbeddedSessionLimit+1)
			recalculateV1GrowthHistoryCRC(history)
		}},
		{name: "too many days", mutate: func(history []byte) {
			binary.LittleEndian.PutUint32(history[20:24], v1EmbeddedDayLimit+1)
			recalculateV1GrowthHistoryCRC(history)
		}},
		{name: "count and payload layout disagree", mutate: func(history []byte) {
			binary.LittleEndian.PutUint32(history[16:20], 0)
			recalculateV1GrowthHistoryCRC(history)
		}},
		{name: "checksum mismatch", mutate: func(history []byte) { history[len(history)-1] ^= 0xff }},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			path, _ := writeV1Fixture(t)
			raw, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			history := marshalV1GrowthHistoryForTest()
			test.mutate(history)
			copy(raw[int(v1HistoryOffset):], history)
			copy(raw[int(v1LiveAOffset):], marshalV1GrowthLiveForTest(1, 10, false))
			if err := os.WriteFile(path, raw, 0o600); err != nil {
				t.Fatal(err)
			}

			values, result, err := readV1MemoryValues(path)
			if err != nil {
				t.Fatalf("StreamFileWithResult() error = %v", err)
			}
			if len(values) != 2 || values[0] != 11 || values[1] != 22 {
				t.Fatalf("event data changed: %v", values)
			}
			if result.LogGrowth == nil || result.LogGrowth.Live == nil || result.LogGrowth.Live.GeneratedBytes != 10 {
				t.Fatalf("valid live growth was lost: %+v", result.LogGrowth)
			}
			if len(result.LogGrowth.Sessions) != 0 || len(result.LogGrowth.Days) != 0 {
				t.Fatalf("invalid history leaked into result: %+v", result.LogGrowth)
			}
			if !strings.Contains(strings.Join(result.Warnings, "\n"), "invalid log-growth history") {
				t.Fatalf("warnings = %v", result.Warnings)
			}
		})
	}
}

func TestV1ReaderKeepsValidHistoryWhenBothLiveCopiesAreDamaged(t *testing.T) {
	path, _ := writeV1Fixture(t)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	copy(raw[int(v1HistoryOffset):], marshalV1GrowthHistoryForTest())
	first := marshalV1GrowthLiveForTest(1, 10, false)
	second := marshalV1GrowthLiveForTest(2, 20, true)
	first[len(first)-1] ^= 0xff
	second[len(second)-1] ^= 0xff
	copy(raw[int(v1LiveAOffset):], first)
	copy(raw[int(v1LiveBOffset):], second)
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		t.Fatal(err)
	}

	result, err := StreamFileWithResult(path, nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.LogGrowth == nil || result.LogGrowth.Generation != 7 || result.LogGrowth.Live != nil {
		t.Fatalf("growth = %+v", result.LogGrowth)
	}
	if !strings.Contains(strings.Join(result.Warnings, "\n"), "live summary") {
		t.Fatalf("warnings = %v", result.Warnings)
	}
}

func TestV1ReaderDecodesLogGrowthStateMatrix(t *testing.T) {
	const limit = uint64(1024 * 1024)
	tests := []struct {
		name    string
		session LogGrowthSession
	}{
		{
			name: "below limit",
			session: LogGrowthSession{
				DayKey:               20260701,
				StartedAtMS:          100,
				EndedAtMS:            200,
				ConfiguredLimitBytes: limit,
				MaximumRetainedBytes: limit / 2,
				GeneratedBytes:       limit / 2,
				Completed:            true,
			},
		},
		{
			name: "repeated overflow",
			session: LogGrowthSession{
				DayKey:               20260702,
				StartedAtMS:          300,
				EndedAtMS:            500,
				ConfiguredLimitBytes: limit,
				MaximumRetainedBytes: limit,
				GeneratedBytes:       5 * limit,
				OverflowCount:        4,
				EvictedChunkCount:    12,
				EvictedBytes:         4 * limit,
				FirstOverflowAtMS:    350,
				LastOverflowAtMS:     490,
				Completed:            true,
			},
		},
		{
			name: "active session",
			session: LogGrowthSession{
				DayKey:               20260703,
				StartedAtMS:          600,
				EndedAtMS:            650,
				ConfiguredLimitBytes: limit,
				MaximumRetainedBytes: limit / 4,
				GeneratedBytes:       limit / 4,
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			path, _ := writeV1Fixture(t)
			raw, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			copy(raw[int(v1LiveAOffset):], marshalV1GrowthSessionForTest(1, test.session))
			if err := os.WriteFile(path, raw, 0o600); err != nil {
				t.Fatal(err)
			}

			result, err := StreamFileWithResult(path, nil)
			if err != nil {
				t.Fatal(err)
			}
			if result.LogGrowth == nil || result.LogGrowth.Live == nil {
				t.Fatalf("growth = %+v", result.LogGrowth)
			}
			actual := result.LogGrowth.Live
			if actual.DayKey != test.session.DayKey ||
				actual.ConfiguredLimitBytes != test.session.ConfiguredLimitBytes ||
				actual.MaximumRetainedBytes != test.session.MaximumRetainedBytes ||
				actual.GeneratedBytes != test.session.GeneratedBytes ||
				actual.OverflowCount != test.session.OverflowCount ||
				actual.EvictedChunkCount != test.session.EvictedChunkCount ||
				actual.EvictedBytes != test.session.EvictedBytes ||
				actual.Completed != test.session.Completed {
				t.Fatalf("live growth = %+v, want %+v", actual, test.session)
			}
		})
	}
}

func writeV1Fixture(t *testing.T) (string, int) {
	t.Helper()
	const arenaCapacity = 512
	headerBytes, normalized, err := encodeFileHeader(DefaultSegmentHeader())
	if err != nil {
		t.Fatal(err)
	}
	first := v1TestChunk(t, normalized, 4, 11)
	second := v1TestChunk(t, normalized, 5, 22)
	firstPosition := arenaCapacity - len(first) - 8
	if firstPosition <= len(second) {
		t.Fatalf("fixture chunks are unexpectedly large: %d, %d", len(first), len(second))
	}

	raw := make([]byte, int(v1ArenaOffset)+arenaCapacity)
	copy(raw, []byte{'J', 'H', 'L', 'O', 'G', '\r', '\n', CurrentFormatMarker, CurrentFormatMajor, CurrentFormatMinor})
	copy(raw[int(v1FileHeaderOffset):], headerBytes[len(Magic):])
	copy(raw[int(v1ArenaOffset)+firstPosition:], first)
	copy(raw[int(v1ArenaOffset):], second)

	stateA := v1TestSuperblock{
		generation: 1,
		head:       uint64(firstPosition),
		tail:       uint64(firstPosition + len(first)),
		used:       uint64(len(first)),
		first:      4,
		next:       5,
		count:      1,
	}
	stateB := v1TestSuperblock{
		generation: 2,
		head:       uint64(firstPosition),
		tail:       uint64(len(second)),
		used:       uint64(len(first) + len(second)),
		first:      4,
		next:       6,
		count:      2,
		wraps:      1,
		evicted:    1,
	}
	copy(raw[int(v1SuperblockAOffset):], marshalV1TestSuperblock(arenaCapacity, stateA))
	copy(raw[int(v1SuperblockBOffset):], marshalV1TestSuperblock(arenaCapacity, stateB))

	path := filepath.Join(t.TempDir(), "format-1-0.jhlog")
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		t.Fatal(err)
	}
	return path, firstPosition
}

func writeV1FixtureWithUnallocatedTail(t *testing.T) string {
	t.Helper()
	const arenaCapacity = 512
	headerBytes, normalized, err := encodeFileHeader(DefaultSegmentHeader())
	if err != nil {
		t.Fatal(err)
	}
	first := v1TestChunk(t, normalized, 4, 11)
	second := v1TestChunk(t, normalized, 5, 22)
	firstPosition := arenaCapacity - len(first) - 128
	if firstPosition <= len(second) {
		t.Fatalf("fixture chunks are unexpectedly large: %d, %d", len(first), len(second))
	}
	firstEnd := firstPosition + len(first)
	raw := make([]byte, int(v1ArenaOffset)+firstEnd)
	copy(raw, []byte{'J', 'H', 'L', 'O', 'G', '\r', '\n', CurrentFormatMarker, CurrentFormatMajor, CurrentFormatMinor})
	copy(raw[int(v1FileHeaderOffset):], headerBytes[len(Magic):])
	copy(raw[int(v1ArenaOffset)+firstPosition:], first)
	copy(raw[int(v1ArenaOffset):], second)

	stateA := v1TestSuperblock{
		generation: 1,
		head:       uint64(firstPosition),
		tail:       uint64(firstEnd),
		used:       uint64(len(first)),
		first:      4,
		next:       5,
		count:      1,
	}
	stateB := v1TestSuperblock{
		generation: 2,
		head:       uint64(firstPosition),
		tail:       uint64(len(second)),
		used:       uint64(len(first) + len(second)),
		first:      4,
		next:       6,
		count:      2,
		wraps:      1,
		evicted:    1,
	}
	copy(raw[int(v1SuperblockAOffset):], marshalV1TestSuperblock(arenaCapacity, stateA))
	copy(raw[int(v1SuperblockBOffset):], marshalV1TestSuperblock(arenaCapacity, stateB))

	path := filepath.Join(t.TempDir(), "format-1-0-unallocated-tail.jhlog")
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func FuzzV1ReaderNeverPanicsOnBoundedInput(f *testing.F) {
	path, _ := writeV1FixtureForFuzz(f)
	valid, err := os.ReadFile(path)
	if err != nil {
		f.Fatal(err)
	}
	f.Add(valid)
	f.Add([]byte{})
	f.Add([]byte{'J', 'H', 'L', 'O', 'G', '\r', '\n', CurrentFormatMarker, CurrentFormatMajor, CurrentFormatMinor})

	f.Fuzz(func(t *testing.T, raw []byte) {
		if len(raw) > 2*1024*1024 {
			return
		}
		path := filepath.Join(t.TempDir(), "fuzz.jhlog")
		if err := os.WriteFile(path, raw, 0o600); err != nil {
			t.Fatal(err)
		}
		_, _ = StreamFileWithResult(path, nil)
	})
}

func writeV1FixtureForFuzz(t testing.TB) (string, int) {
	t.Helper()
	const arenaCapacity = 512
	headerBytes, normalized, err := encodeFileHeader(DefaultSegmentHeader())
	if err != nil {
		t.Fatal(err)
	}
	first := v1TestChunk(t, normalized, 4, 11)
	second := v1TestChunk(t, normalized, 5, 22)
	firstPosition := arenaCapacity - len(first) - 8
	raw := make([]byte, int(v1ArenaOffset)+arenaCapacity)
	copy(raw, []byte{'J', 'H', 'L', 'O', 'G', '\r', '\n', CurrentFormatMarker, CurrentFormatMajor, CurrentFormatMinor})
	copy(raw[int(v1FileHeaderOffset):], headerBytes[len(Magic):])
	copy(raw[int(v1ArenaOffset)+firstPosition:], first)
	copy(raw[int(v1ArenaOffset):], second)
	copy(raw[int(v1SuperblockAOffset):], marshalV1TestSuperblock(arenaCapacity, v1TestSuperblock{
		generation: 1, head: uint64(firstPosition), tail: uint64(firstPosition + len(first)), used: uint64(len(first)), first: 4, next: 5, count: 1,
	}))
	copy(raw[int(v1SuperblockBOffset):], marshalV1TestSuperblock(arenaCapacity, v1TestSuperblock{
		generation: 2, head: uint64(firstPosition), tail: uint64(len(second)), used: uint64(len(first) + len(second)), first: 4, next: 6, count: 2, wraps: 1, evicted: 1,
	}))
	path := filepath.Join(t.TempDir(), "format-1-0-fuzz-seed.jhlog")
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		t.Fatal(err)
	}
	return path, firstPosition
}

func v1TestChunk(t testing.TB, header SegmentHeader, sequence uint64, pssKB uint64) []byte {
	t.Helper()
	record, _, _, err := encodeRecord(
		Event{Type: EventMemory, Memory: &MemoryEvent{PSSKB: pssKB}},
		recordEncodeState{lastElapsedUS: int64(header.SegmentStartElapsedUS)},
	)
	if err != nil {
		t.Fatal(err)
	}
	rawCRC := crc32.ChecksumIEEE(record)
	chunk := make([]byte, v1ChunkHeaderBytes+len(record)+v1CommitTrailerBytes)
	copy(chunk, v1ChunkMagic)
	binary.LittleEndian.PutUint16(chunk[4:6], v1ChunkHeaderBytes)
	binary.LittleEndian.PutUint64(chunk[8:16], sequence)
	binary.LittleEndian.PutUint32(chunk[16:20], uint32(len(record)))
	binary.LittleEndian.PutUint32(chunk[20:24], uint32(len(record)))
	binary.LittleEndian.PutUint32(chunk[24:28], 1)
	binary.LittleEndian.PutUint32(chunk[28:32], rawCRC)
	binary.LittleEndian.PutUint32(chunk[32:36], crc32.ChecksumIEEE(chunk[:32]))
	copy(chunk[v1ChunkHeaderBytes:], record)
	trailer := chunk[v1ChunkHeaderBytes+len(record):]
	copy(trailer, v1CommitMagic)
	binary.LittleEndian.PutUint64(trailer[4:12], sequence)
	binary.LittleEndian.PutUint32(trailer[12:16], uint32(len(record)))
	binary.LittleEndian.PutUint32(trailer[16:20], uint32(len(record)))
	binary.LittleEndian.PutUint32(trailer[20:24], rawCRC)
	return chunk
}

type v1TestSuperblock struct {
	generation uint64
	head       uint64
	tail       uint64
	used       uint64
	first      uint64
	next       uint64
	count      uint64
	wraps      uint64
	evicted    uint64
}

func marshalV1TestSuperblock(arenaCapacity int, state v1TestSuperblock) []byte {
	raw := make([]byte, v1SuperblockBytes)
	copy(raw, v1SuperblockMagic)
	binary.LittleEndian.PutUint16(raw[4:6], v1SuperblockSchema)
	values := []uint64{
		state.generation,
		uint64(arenaCapacity),
		state.head,
		state.tail,
		state.used,
		state.first,
		state.next,
		state.count,
		state.wraps,
		state.evicted,
		state.evicted * 64,
		state.evicted*64 + state.used,
		uint64(v1ArenaOffset) + uint64(arenaCapacity),
	}
	for index, value := range values {
		binary.LittleEndian.PutUint64(raw[8+index*8:], value)
	}
	binary.LittleEndian.PutUint32(raw[len(raw)-4:], crc32.ChecksumIEEE(raw[:len(raw)-4]))
	return raw
}

func readV1MemoryValues(path string) ([]uint64, StreamResult, error) {
	values := make([]uint64, 0, 2)
	result, err := StreamFileWithResult(path, func(event Event, _ map[uint64]string) error {
		if event.Memory != nil {
			values = append(values, event.Memory.PSSKB)
		}
		return nil
	})
	return values, result, err
}

func marshalV1GrowthHistoryForTest() []byte {
	raw := make([]byte, v1HistoryHeaderBytes+v1HistorySessionBytes+v1HistoryDayBytes)
	copy(raw, v1GrowthHistoryMagic)
	raw[4] = CurrentFormatMajor
	raw[5] = CurrentFormatMinor
	binary.LittleEndian.PutUint16(raw[6:8], v1HistoryHeaderBytes)
	binary.LittleEndian.PutUint32(raw[8:12], uint32(len(raw)))
	binary.LittleEndian.PutUint16(raw[12:14], v1HistorySessionBytes)
	binary.LittleEndian.PutUint16(raw[14:16], v1HistoryDayBytes)
	binary.LittleEndian.PutUint32(raw[16:20], 1)
	binary.LittleEndian.PutUint32(raw[20:24], 1)
	binary.LittleEndian.PutUint64(raw[24:32], 7)
	binary.LittleEndian.PutUint64(raw[32:40], 1_800_000_000_000)
	session := raw[v1HistoryHeaderBytes : v1HistoryHeaderBytes+v1HistorySessionBytes]
	binary.LittleEndian.PutUint64(session[0:8], 11)
	binary.LittleEndian.PutUint32(session[8:12], 20270115)
	binary.LittleEndian.PutUint32(session[12:16], 1)
	for index, value := range []uint64{100, 200, 1_000, 900, 500, 2, 3, 400, 150, 190} {
		binary.LittleEndian.PutUint64(session[16+index*8:], value)
	}
	day := raw[v1HistoryHeaderBytes+v1HistorySessionBytes:]
	binary.LittleEndian.PutUint32(day[0:4], 20270115)
	for index, value := range []uint64{1, 100, 500, 900, 900, 1, 6, 7, 800} {
		binary.LittleEndian.PutUint64(day[8+index*8:], value)
	}
	binary.LittleEndian.PutUint32(raw[60:64], crc32.ChecksumIEEE(raw))
	return raw
}

func recalculateV1GrowthHistoryCRC(raw []byte) {
	for index := 60; index < 64; index++ {
		raw[index] = 0
	}
	binary.LittleEndian.PutUint32(raw[60:64], crc32.ChecksumIEEE(raw))
}

func marshalV1GrowthLiveForTest(generation, generated uint64, completed bool) []byte {
	return marshalV1GrowthSessionForTest(generation, LogGrowthSession{
		DayKey:               20270115,
		StartedAtMS:          100,
		EndedAtMS:            200,
		ConfiguredLimitBytes: 1_000,
		MaximumRetainedBytes: 900,
		GeneratedBytes:       generated,
		OverflowCount:        2,
		EvictedChunkCount:    3,
		EvictedBytes:         400,
		FirstOverflowAtMS:    150,
		LastOverflowAtMS:     190,
		Completed:            completed,
	})
}

func marshalV1GrowthSessionForTest(generation uint64, session LogGrowthSession) []byte {
	raw := make([]byte, v1LiveBytes)
	copy(raw, v1GrowthLiveMagic)
	raw[4] = CurrentFormatMajor
	raw[5] = CurrentFormatMinor
	binary.LittleEndian.PutUint16(raw[6:8], uint16(v1LiveBytes))
	binary.LittleEndian.PutUint64(raw[8:16], generation)
	binary.LittleEndian.PutUint64(raw[16:24], 1)
	binary.LittleEndian.PutUint64(raw[24:32], 2)
	binary.LittleEndian.PutUint32(raw[32:36], session.DayKey)
	if session.Completed {
		binary.LittleEndian.PutUint32(raw[36:40], 1)
	}
	for index, value := range []uint64{
		session.StartedAtMS,
		session.EndedAtMS,
		session.ConfiguredLimitBytes,
		session.MaximumRetainedBytes,
		session.GeneratedBytes,
		session.OverflowCount,
		session.EvictedChunkCount,
		session.EvictedBytes,
		session.FirstOverflowAtMS,
		session.LastOverflowAtMS,
	} {
		binary.LittleEndian.PutUint64(raw[40+index*8:], value)
	}
	binary.LittleEndian.PutUint32(raw[len(raw)-4:], crc32.ChecksumIEEE(raw[:len(raw)-4]))
	return raw
}
