// Code generated by wire/generate.py from wire/jhlog-v5.json. DO NOT EDIT.

package jhlog

const FormatMarker = 0x81
const FormatMajor = 5
const FormatMinor = 0
const FormatPatch = 0
const FormatVersionString = "5.0.0"
const HeaderSchemaV2 uint64 = 2
const magicSize = 11

const (
	maxHeaderPayloadSize     = 4096
	defaultRawChunkTarget    = 65536
	maxRawChunkSize          = 262144
	chunkHeaderSize          = 32
	commitTrailerSize        = 20
	maxMicroPageRows         = 128
	maxMicroPagePayloadBytes = 49152
	MaxRuntimeCallBlockRows  = 128
	processScopeHashSize     = 32
	segmentDigestSize        = 32
	maxStoredChunkSize       = 524288

	FeatureChunkCRCCommit            uint64 = 1 << 0
	FeatureLengthDelimited           uint64 = 1 << 1
	FeatureSymbolRefs                uint64 = 1 << 2
	FeatureProducerMetadata          uint64 = 1 << 3
	FeatureChunkLocalContext         uint64 = 1 << 4
	FeatureQualityRecords            uint64 = 1 << 5
	FeatureEmbeddedStableSymbols     uint64 = 1 << 6
	FeatureLogGrowthRecords          uint64 = 1 << 7
	FeatureExactEventAdmission       uint64 = 1 << 8
	FeatureProcessScope              uint64 = 1 << 9
	FeatureColumnarRuntimeCalls      uint64 = 1 << 10
	FeatureSegmentDigestChain        uint64 = 1 << 11
	FeatureProcessRoster             uint64 = 1 << 12
	FeatureOperationLifecycle        uint64 = 1 << 13
	FeatureDatabaseLifecycle         uint64 = 1 << 14
	FeatureProcessState              uint64 = 1 << 15
	FeatureAndroidComponents         uint64 = 1 << 16
	FeatureBinderIPC                 uint64 = 1 << 17
	FeatureCompactPayloads           uint64 = 1 << 18
	FeatureRuntimeEdgeRegistry       uint64 = 1 << 19
	FeatureColumnarMicroPages        uint64 = 1 << 20
	FeatureDeltaControlRecords       uint64 = 1 << 21
	FeatureFrontCodedDictionary      uint64 = 1 << 23
	FeatureRuntimeEdgeBitPlanes      uint64 = 1 << 24
	FeatureImplicitStableAliases     uint64 = 1 << 25
	FeatureColumnarRuntimeEdgeTuples uint64 = 1 << 26
	FeatureGZIPChunks                uint64 = 1 << 0
	FeatureDatabaseTransactionDelta  uint64 = 1 << 1
	FeatureColumnarDatabasePages     uint64 = 1 << 2
	FeatureSegmentDictionaryTokens   uint64 = 1 << 3
	FeatureRuntimeNumericColumns     uint64 = 1 << 4
	FeatureRANSMicroPageSections     uint64 = 1 << 5
	RequiredFeatures                 uint64 = 0x7bfffff
	BestEffortFeatures               uint64 = RequiredFeatures &^ FeatureExactEventAdmission
	OptionalFeatures                 uint64 = 0x1f
	RawOptionalFeatures              uint64 = 0x3e
	compressionFeatures              uint64 = FeatureGZIPChunks | FeatureRANSMicroPageSections

	chunkFlagGZIP   uint16 = 1 << 0
	chunkFlagFinal  uint16 = 1 << 1
	chunkKnownFlags        = chunkFlagGZIP | chunkFlagFinal
)

var Magic = []byte{0x4a, 0x48, 0x4c, 0x4f, 0x47, 0x0d, 0x0a, 0x81, 0x05, 0x00, 0x00}
var chunkMagic = [4]byte{0x4a, 0x48, 0x43, 0x31}
var commitMagic = [4]byte{0x4a, 0x48, 0x43, 0x4d}

const (
	ProcessScopeUnknown ProcessScope = iota
	ProcessScopeAll
	ProcessScopeMainOnly
	ProcessScopeAllowlist
)

const (
	EventDictionary          EventType = 1
	EventSession             EventType = 2
	EventContext             EventType = 3
	EventHTTP                EventType = 4
	EventUIWindow            EventType = 5
	EventStall               EventType = 6
	EventMemory              EventType = 7
	EventRetained            EventType = 8
	EventCounter             EventType = 9
	EventGauge               EventType = 10
	EventOperation           EventType = 11
	EventLogSpam             EventType = 12
	EventProblem             EventType = 13
	EventRuntimeCall         EventType = 14
	EventQualitySnapshot     EventType = 15
	EventSegmentEnd          EventType = 16
	EventLogGrowth           EventType = 17
	EventProcessExit         EventType = 18
	EventIO                  EventType = 19
	EventWorker              EventType = 20
	EventWebSocket           EventType = 21
	EventDatabase            EventType = 22
	EventDatabaseTransaction EventType = 23
	EventProcessState        EventType = 24
	EventAndroidComponent    EventType = 25
	EventBinderTransaction   EventType = 26
	eventMicroPage           EventType = 27
)

const (
	EnvelopeHasTime       EnvelopeFlag = 1 << 0
	EnvelopeHasThread     EnvelopeFlag = 1 << 1
	EnvelopeHasContext    EnvelopeFlag = 1 << 2
	EnvelopeSameContext   EnvelopeFlag = 1 << 3
	EnvelopeHasAttributes EnvelopeFlag = 1 << 4
)
