#!/usr/bin/env python3
import argparse
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "wire" / "jhlog-v5.json"
KOTLIN_PATH = ROOT / "android" / "jankhunter-runtime" / "src" / "main" / "kotlin" / "io" / "jankhunter" / "runtime" / "internal" / "io" / "Jhlog.kt"
GO_PATH = ROOT / "cli" / "internal" / "jhlog" / "wire_generated.go"
FIXTURE_DIR = ROOT / "wire" / "testdata"
BEGIN = "    // <wire-generated>"
END = "    // </wire-generated>"


def bit_mask(entries):
    return sum(1 << entry["bit"] for entry in entries)


def profile_mask(entries, profile):
    return bit_mask(entry for entry in entries if profile in entry["profiles"])


def kotlin_byte_array(name, raw):
    lines = [f"    val {name} = byteArrayOf("]
    lines.extend(f"        0x{value:02x}.toByte()," for value in raw)
    lines.append("    )")
    return lines


def render_kotlin(spec):
    fmt = spec["format"]
    required = bit_mask(spec["required_features"])
    gzip_optional = profile_mask(spec["optional_features"], "gzip")
    raw_optional = profile_mask(spec["optional_features"], "raw")
    lines = [BEGIN, "    // Generated by wire/generate.py from wire/jhlog-v5.json. Do not edit."]
    lines += [
        f"    const val FORMAT_MARKER = 0x{fmt['marker']:x}",
        f"    const val FORMAT_MAJOR = {fmt['major']}",
        f"    const val FORMAT_MINOR = {fmt['minor']}",
        f"    const val FORMAT_PATCH = {fmt['patch']}",
        f"    const val FORMAT_VERSION = \"{fmt['major']}.{fmt['minor']}.{fmt['patch']}\"",
        f"    const val HEADER_SCHEMA = {fmt['header_schema']}L",
    ]
    for limit in spec["limits"]:
        if "kotlin" in limit:
            lines.append(f"    const val {limit['kotlin']} = {limit['value']}")
    lines += [
        f"    const val REQUIRED_FEATURES = 0x{required:x}L",
        f"    const val OPTIONAL_FEATURES = 0x{gzip_optional:x}L",
        f"    const val RAW_OPTIONAL_FEATURES = 0x{raw_optional:x}L",
    ]
    for entry in spec["required_features"] + spec["optional_features"]:
        lines.append(f"    const val {entry['kotlin']} = 1L shl {entry['bit']}")
    exact = next(entry for entry in spec["required_features"] if entry["kotlin"] == "FEATURE_EXACT_EVENT_ADMISSION")
    lines.append(f"    const val BEST_EFFORT_FEATURES = REQUIRED_FEATURES and {exact['kotlin']}.inv()")
    for entry in spec["process_scopes"]:
        lines.append(f"    const val {entry['kotlin']} = {entry['value']}L")
    for entry in spec["chunk_flags"]:
        lines.append(f"    const val {entry['kotlin']} = 1 shl {entry['bit']}")
    for entry in spec["envelope_flags"] + spec["context_flags"]:
        lines.append(f"    const val {entry['kotlin']} = 1L shl {entry['bit']}")
    for entry in spec["record_types"]:
        lines.append(f"    const val {entry['kotlin']} = {entry['value']}")
    file_magic = bytes.fromhex(fmt["prefix_hex"]) + bytes((fmt["marker"], fmt["major"], fmt["minor"], fmt["patch"]))
    lines += kotlin_byte_array("FILE_MAGIC", file_magic)
    lines += kotlin_byte_array("CHUNK_MAGIC", bytes.fromhex(fmt["chunk_magic_hex"]))
    lines += kotlin_byte_array("COMMIT_MAGIC", bytes.fromhex(fmt["commit_magic_hex"]))
    lines.append(END)
    return "\n".join(lines)


def render_go(spec):
    fmt = spec["format"]
    required = bit_mask(spec["required_features"])
    gzip_optional = profile_mask(spec["optional_features"], "gzip")
    raw_optional = profile_mask(spec["optional_features"], "raw")
    lines = [
        "// Code generated by wire/generate.py from wire/jhlog-v5.json. DO NOT EDIT.",
        "",
        "package jhlog",
        "",
        f"const FormatMarker = 0x{fmt['marker']:x}",
        f"const FormatMajor = {fmt['major']}",
        f"const FormatMinor = {fmt['minor']}",
        f"const FormatPatch = {fmt['patch']}",
        f"const FormatVersionString = \"{fmt['major']}.{fmt['minor']}.{fmt['patch']}\"",
        f"const HeaderSchemaV2 uint64 = {fmt['header_schema']}",
        f"const magicSize = {len(bytes.fromhex(fmt['prefix_hex'])) + 4}",
        "",
        "const (",
    ]
    for limit in spec["limits"]:
        if "go" in limit:
            lines.append(f"\t{limit['go']} = {limit['value']}")
    lines.append("")
    for entry in spec["required_features"] + spec["optional_features"]:
        lines.append(f"\t{entry['go']} uint64 = 1 << {entry['bit']}")
    exact = next(entry for entry in spec["required_features"] if entry["go"] == "FeatureExactEventAdmission")
    lines += [
        f"\tRequiredFeatures uint64 = 0x{required:x}",
        f"\tBestEffortFeatures uint64 = RequiredFeatures &^ {exact['go']}",
        f"\tOptionalFeatures uint64 = 0x{gzip_optional:x}",
        f"\tRawOptionalFeatures uint64 = 0x{raw_optional:x}",
        "\tcompressionFeatures uint64 = FeatureGZIPChunks | FeatureRANSMicroPageSections",
        "",
    ]
    for entry in spec["chunk_flags"]:
        lines.append(f"\t{entry['go']} uint16 = 1 << {entry['bit']}")
    lines.append("\tchunkKnownFlags = chunkFlagGZIP | chunkFlagFinal")
    lines.append(")")
    prefix = list(bytes.fromhex(fmt["prefix_hex"]))
    magic_values = prefix + [fmt["marker"], fmt["major"], fmt["minor"], fmt["patch"]]
    lines += [
        "",
        "var Magic = []byte{" + ", ".join(f"0x{value:02x}" for value in magic_values) + "}",
        "var chunkMagic = [4]byte{" + ", ".join(f"0x{value:02x}" for value in bytes.fromhex(fmt["chunk_magic_hex"])) + "}",
        "var commitMagic = [4]byte{" + ", ".join(f"0x{value:02x}" for value in bytes.fromhex(fmt["commit_magic_hex"])) + "}",
        "",
        "const (",
        "\tProcessScopeUnknown ProcessScope = iota",
    ]
    for entry in spec["process_scopes"]:
        lines.append(f"\t{entry['go']}")
    lines += [")", "", "const ("]
    for entry in spec["record_types"]:
        lines.append(f"\t{entry['go']} EventType = {entry['value']}")
    lines += [")", "", "const ("]
    for entry in spec["envelope_flags"]:
        lines.append(f"\t{entry['go']} EnvelopeFlag = 1 << {entry['bit']}")
    lines += [")", ""]
    formatted = subprocess.run(
        ["gofmt"],
        input="\n".join(lines),
        text=True,
        capture_output=True,
        check=True,
    )
    return formatted.stdout


def replace_generated_region(source, generated):
    start = source.find(BEGIN)
    finish = source.find(END)
    if start < 0 or finish < start:
        raise ValueError("Jhlog.kt generated markers are missing")
    finish += len(END)
    return source[:start] + generated + source[finish:]


def update(path, expected, check):
    actual = path.read_text() if path.exists() else ""
    if actual == expected:
        return True
    if check:
        print(f"stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected)
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads(SPEC_PATH.read_text())
    kotlin_source = KOTLIN_PATH.read_text()
    kotlin_expected = replace_generated_region(kotlin_source, render_kotlin(spec))
    valid = update(KOTLIN_PATH, kotlin_expected, args.check)
    valid = update(GO_PATH, render_go(spec), args.check) and valid
    for name, payload in spec["goldens"].items():
        path = FIXTURE_DIR / name
        expected = bytes.fromhex(payload)
        actual = path.read_bytes() if path.exists() else b""
        if actual == expected:
            continue
        if args.check:
            print(f"stale generated fixture: {path.relative_to(ROOT)}", file=sys.stderr)
            valid = False
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)
    if not valid:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
